name: Continuous Integration

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.sh'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.sh'
  workflow_dispatch:

jobs:
  pi4j-builder-base:
    name: Build `pi4j-builder-base`
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1       
      - name: Build image for `pi4j-builder-base`
        run: |
         cd pi4j-builder-base
         ./build.sh --push

  pi4j-builder-native:
    needs: [pi4j-builder-base]
    name: Build `pi4j-builder-native`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build image for `pi4j-builder-native`
        run: |
         cd pi4j-builder-native
         ./build.sh --push
         
  pi4j-builder-2_0:
    needs: [pi4j-builder-base,pi4j-builder-native]
    name: Build `pi4j-builder-2.0`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build image for `pi4j-builder-2.0`
        run: |
         cd pi4j-builder-2.0
         ./build.sh --push
